import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'notifications.dart';
import '../theme.dart';

class MeScreen extends StatefulWidget{const MeScreen({super.key});@override State<MeScreen> createState()=>_MeScreenState();}
class _MeScreenState extends State<MeScreen>{
 final sb=Supabase.instance.client;final _name=TextEditingController(),_phone=TextEditingController(),_email=TextEditingController(),_pass=TextEditingController();Map<String,dynamic>? _profile;bool _busy=false;int _unread=0,_trips=0,_saved=0,_reviews=0;
 @override void initState(){super.initState();_loadProfile();}
 Future<void> _loadProfile()async{final u=sb.auth.currentUser;if(u==null)return;try{final r=await Future.wait([sb.from('profiles').select().eq('id',u.id).maybeSingle(),sb.from('notifications').select('id').eq('user_id',u.id).eq('is_read',false),sb.from('saved_places').select('id').eq('user_id',u.id),sb.from('reviews').select('id').eq('user_id',u.id),sb.from('bookings').select('id').eq('user_id',u.id),sb.from('reservations').select('id').eq('user_id',u.id)]);final p=r[0] as Map?;if(mounted)setState((){_profile=p==null?null:Map<String,dynamic>.from(p);_name.text=p?['full_name']??'';_phone.text=p?['phone']??'';_unread=(r[1] as List).length;_saved=(r[2] as List).length;_reviews=(r[3] as List).length;_trips=(r[4] as List).length+(r[5] as List).length;});}catch(_){}}
 void _snack(String m){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(m)));}
 Future<void> _signIn()async{setState(()=>_busy=true);try{await sb.auth.signInWithPassword(email:_email.text.trim(),password:_pass.text);await _loadProfile();}on AuthException catch(e){_snack(e.message);}finally{if(mounted)setState(()=>_busy=false);}}
 Future<void> _signUp()async{final n=_name.text.trim(),e=_email.text.trim(),p=_pass.text;if(n.isEmpty||!e.contains('@')||p.length<6){_snack('Enter your name, a valid email and a password of at least 6 characters.');return;}setState(()=>_busy=true);try{final res=await sb.auth.signUp(email:e,password:p);if(res.user==null){_snack('Sign up failed.');return;}if(res.session==null){_snack('Account created. Check your email to confirm.');return;}await sb.from('profiles').upsert({'id':res.user!.id,'full_name':n});await _loadProfile();}on AuthException catch(e){_snack(e.message);}finally{if(mounted)setState(()=>_busy=false);}}
 Future<void> _edit()async{final n=TextEditingController(text:_name.text),p=TextEditingController(text:_phone.text);final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Profile settings'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Full real name')),const SizedBox(height:10),TextField(controller:p,decoration:const InputDecoration(labelText:'Phone number'))]),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:()async{final u=sb.auth.currentUser;if(u==null)return;await sb.from('profiles').update({'full_name':n.text.trim(),'phone':p.text.trim().isEmpty?null:p.text.trim()}).eq('id',u.id);if(mounted)Navigator.pop(context,true);},child:const Text('Save'))]));n.dispose();p.dispose();if(ok==true)_loadProfile();}
 Future<void> _signOut()async{final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Sign out?'),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Sign out'))]));if(ok==true)await sb.auth.signOut();}
 void _dialog(String t,String b){showDialog(context:context,builder:(_)=>AlertDialog(title:Text(t),content:Text(b),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Close'))]));}
 @override void dispose(){_name.dispose();_phone.dispose();_email.dispose();_pass.dispose();super.dispose();}
 @override Widget build(BuildContext context){final u=sb.auth.currentUser;if(u==null)return Scaffold(backgroundColor:FT.obsidian,body:SafeArea(child:ListView(padding:const EdgeInsets.all(22),children:[const SizedBox(height:45),const Text('Welcome to FineTime',style:TextStyle(color:FT.ivory,fontSize:32,fontWeight:FontWeight.w800,fontFamily:'serif')),const SizedBox(height:8),const Text('Discover. Dine. Stay.',style:TextStyle(color:FT.muted)),const SizedBox(height:30),TextField(controller:_name,decoration:const InputDecoration(labelText:'Full real name')),const SizedBox(height:10),TextField(controller:_email,decoration:const InputDecoration(labelText:'Email')),const SizedBox(height:10),TextField(controller:_pass,obscureText:true,decoration:const InputDecoration(labelText:'Password')),const SizedBox(height:18),FilledButton(onPressed:_busy?null:_signUp,child:Text(_busy?'Working…':'Create Account')),TextButton(onPressed:_busy?null:_signIn,child:const Text('Already have an account? Sign in'))])));final name=(_profile?['full_name']??u.email??'FineTime member').toString();final initial=name.trim().isEmpty?'F':name.trim()[0].toUpperCase();return Scaffold(backgroundColor:FT.obsidian,body:SafeArea(bottom:false,child:ListView(padding:const EdgeInsets.fromLTRB(30,30,30,110),children:[
 Center(child:Container(width:112,height:112,decoration:BoxDecoration(shape:BoxShape.circle,gradient:FT.goldGradient),padding:const EdgeInsets.all(3),child:Container(decoration:const BoxDecoration(shape:BoxShape.circle,color:Color(0xFF4B2B12)),child:Center(child:Text(initial,style:const TextStyle(color:FT.ivory,fontSize:46,fontFamily:'serif')))))),
 const SizedBox(height:20),Center(child:Text(name,style:const TextStyle(color:FT.ivory,fontSize:30,fontWeight:FontWeight.w800,fontFamily:'serif'))),const SizedBox(height:5),const Center(child:Text('FineTime member since 2024',style:TextStyle(color:FT.muted,fontSize:13))),const SizedBox(height:15),Center(child:Row(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.star,color:FT.gold,size:20),const SizedBox(width:5),const Text('4.9',style:TextStyle(color:FT.gold,fontWeight:FontWeight.w700)),Text(' ('+_reviews.toString()+' reviews)',style:const TextStyle(color:FT.muted))])),
 const SizedBox(height:28),Container(decoration:BoxDecoration(color:const Color(0xFF111518),borderRadius:BorderRadius.circular(20),border:Border.all(color:const Color(0xFF252A2D))),child:Row(children:[_stat(_trips.toString(),'Trips'),_line(),_stat(_saved.toString(),'Saved'),_line(),_stat(_reviews.toString(),'Reviews')])),
 const SizedBox(height:28),Container(decoration:BoxDecoration(color:const Color(0xFF111518),borderRadius:BorderRadius.circular(20),border:Border.all(color:const Color(0xFF252A2D))),child:Column(children:[
 _row(Icons.person_outline,'Profile settings',_edit),_row(Icons.notifications_none,'Notifications',()async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>const NotificationsScreen()));await _loadProfile();}),_row(Icons.receipt_long_outlined,'Order history',()=>_dialog('Order history','Your stays, reservations and food orders are available in Trips.')),_row(Icons.star_border,'My reviews',()=>_dialog('My reviews','You have '+_reviews.toString()+' review(s).')),_row(Icons.help_outline,'Help center',()=>_dialog('Help Center','For booking, dining, saved places and account support, contact FineTime support.')),_row(Icons.settings_outlined,'Settings',()=>_dialog('Settings','Your FineTime account settings are available here.'))
 ])),
 const SizedBox(height:24),OutlinedButton(onPressed:_signOut,style:OutlinedButton.styleFrom(foregroundColor:const Color(0xFFE58B80),side:const BorderSide(color:Color(0xFF52241F)),minimumSize:const Size.fromHeight(58),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18))),child:const Text('Sign out'))
 ])));
 }
 Widget _stat(String n,String l)=>Expanded(child:SizedBox(height:95,child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(n,style:const TextStyle(color:FT.gold,fontSize:24,fontWeight:FontWeight.w800,fontFamily:'serif')),const SizedBox(height:5),Text(l,style:const TextStyle(color:FT.muted,fontSize:12))])));
 Widget _line()=>Container(width:1,height:55,color:const Color(0xFF252A2D));
 Widget _row(IconData i,String t,VoidCallback f)=>InkWell(onTap:f,child:Container(height:73,padding:const EdgeInsets.symmetric(horizontal:22),decoration:const BoxDecoration(border:Border(bottom:BorderSide(color:Color(0xFF252A2D)))),child:Row(children:[Icon(i,color:FT.gold,size:25),const SizedBox(width:20),Expanded(child:Text(t,style:const TextStyle(color:FT.ivory,fontSize:15,fontWeight:FontWeight.w600))),const Icon(Icons.chevron_right,color:FT.muted)])));
}
