import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../theme.dart';

class TripsScreen extends StatefulWidget{const TripsScreen({super.key});@override State<TripsScreen> createState()=>_TripsScreenState();}
class _TripsScreenState extends State<TripsScreen>{
 final sb=Supabase.instance.client;List<Map<String,dynamic>> _bookings=[],_reservations=[],_orders=[];bool _loading=true;String? _error;int _tab=0;RealtimeChannel? _realtime;
 @override void initState(){super.initState();_load();final u=sb.auth.currentUser;if(u!=null)_realtime=sb.channel('trips-live-'+u.id)..onPostgresChanges(event:PostgresChangeEvent.all,schema:'public',table:'bookings',callback:(_)=>_load())..onPostgresChanges(event:PostgresChangeEvent.all,schema:'public',table:'reservations',callback:(_)=>_load())..onPostgresChanges(event:PostgresChangeEvent.all,schema:'public',table:'orders',callback:(_)=>_load())..subscribe();}
 DateTime _date(dynamic v)=>DateTime.tryParse(v?.toString()??'')??DateTime(2100);
 Future<void> _load()async{final u=sb.auth.currentUser;if(u==null){if(mounted)setState(()=>_loading=false);return;}try{final r=await Future.wait([sb.from('bookings').select('*, businesses(*), room_types(name)').eq('user_id',u.id).order('created_at',ascending:false),sb.from('reservations').select('*, businesses(*)').eq('user_id',u.id).order('created_at',ascending:false),sb.from('orders').select('*, businesses(*)').eq('user_id',u.id).order('created_at',ascending:false)]);if(mounted)setState(()=>{_bookings=List<Map<String,dynamic>>.from(r[0] as List);_reservations=List<Map<String,dynamic>>.from(r[1] as List);_orders=List<Map<String,dynamic>>.from(r[2] as List);_loading=false;_error=null});}catch(_){if(mounted)setState(()=>{_error='Could not load your trips. Check your connection.';_loading=false});}}
 bool _past(Map d,String type,DateTime today){if(d['status']=='cancelled')return true;if(type=='order')return d['status']=='delivered';return _date(type=='stay'?d['check_out']:d['reservation_date']).isBefore(today);}
 List<Map<String,dynamic>> _items(){final a=<Map<String,dynamic>>[];for(final x in _bookings)a.add({'type':'stay','data':x,'date':x['check_in']});for(final x in _reservations)a.add({'type':'reservation','data':x,'date':x['reservation_date']});for(final x in _orders)a.add({'type':'order','data':x,'date':x['created_at']});a.sort((x,y)=>x['date'].toString().compareTo(y['date'].toString()));return a;}
 String _img(Map b){for(final k in ['image_url','cover_image_url','hero_image_url','photo_url']){final v=b[k]?.toString()??'';if(v.isNotEmpty)return v;}return 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80';}
 @override void dispose(){if(_realtime!=null)sb.removeChannel(_realtime!);super.dispose();}
 @override Widget build(BuildContext context){final now=DateTime.now();final today=DateTime(now.year,now.month,now.day);final items=_items().where((x){final past=_past(x['data'],x['type'],today);if(_tab==2)return past;if(_tab==1)return !past;return !past&&!_date(x['date']).isBefore(today);}).toList();return Scaffold(backgroundColor:FT.obsidian,body:SafeArea(bottom:false,child:RefreshIndicator(onRefresh:_load,color:FT.gold,child:ListView(padding:const EdgeInsets.fromLTRB(30,20,30,32),children:[
 const Text('My trips',style:TextStyle(color:FT.ivory,fontSize:38,fontWeight:FontWeight.w800,fontFamily:'serif')),const SizedBox(height:5),const Text('Your Ethiopian journey',style:TextStyle(color:FT.muted,fontSize:14)),const SizedBox(height:24),
 Container(height:54,padding:const EdgeInsets.all(4),decoration:BoxDecoration(color:const Color(0xFF111518),borderRadius:BorderRadius.circular(18),border:Border.all(color:const Color(0xFF20272A))),child:Row(children:['Upcoming','Past','Cancelled'].asMap().entries.map((e)=>Expanded(child:GestureDetector(onTap:()=>setState(()=>_tab=e.key),child:Container(alignment:Alignment.center,decoration:BoxDecoration(color:_tab==e.key?FT.gold:Colors.transparent,borderRadius:BorderRadius.circular(14)),child:Text(e.value,style:TextStyle(color:_tab==e.key?const Color(0xFF171107):FT.muted,fontWeight:FontWeight.w700))))).toList())),
 const SizedBox(height:28),
 if(sb.auth.currentUser==null)const _Empty('Sign in to see your trips.',Icons.luggage_outlined) else if(_loading)const Padding(padding:EdgeInsets.all(50),child:Center(child:CircularProgressIndicator(color:FT.gold))) else if(_error!=null)...[_Empty(_error!,Icons.cloud_off),FilledButton(onPressed:_load,child:const Text('Retry'))] else if(items.isEmpty)const _Empty('Your stays, reservations and orders will appear here.',Icons.luggage_outlined) else ...[_hero(items.first),const SizedBox(height:32),const Text('Coming up',style:TextStyle(color:FT.ivory,fontSize:26,fontWeight:FontWeight.w800,fontFamily:'serif')),const SizedBox(height:15),...items.take(8).map(_timeline)]
 ]))));}
 Widget _hero(Map x){final d=x['data'] as Map<String,dynamic>;final b=d['businesses'] is Map?Map<String,dynamic>.from(d['businesses']):{};final date=(d['check_in']??d['reservation_date']??'').toString();final room=d['room_types'] is Map?(d['room_types']['name']??'Stay').toString():'FineTime experience';final guests=(d['guests']??d['party_size']??1).toString();return Container(decoration:BoxDecoration(color:const Color(0xFF111518),borderRadius:BorderRadius.circular(24),border:Border.all(color:const Color(0xFF252A2D))),clipBehavior:Clip.antiAlias,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[SizedBox(height:265,width:double.infinity,child:Image.network(_img(b),fit:BoxFit.cover,errorBuilder:(_,__,___)=>Container(color:FT.surface))),Padding(padding:const EdgeInsets.fromLTRB(22,20,22,20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(date.length>=10?date.substring(0,10):date,style:const TextStyle(color:FT.gold,fontWeight:FontWeight.w700,fontSize:12)),const SizedBox(height:10),Text(b['name']??'FineTime stay',style:const TextStyle(color:FT.ivory,fontSize:27,fontWeight:FontWeight.w800,fontFamily:'serif')),const SizedBox(height:6),Text(room+' · '+guests+' guests',style:const TextStyle(color:FT.muted)),const SizedBox(height:20),Row(children:[const Icon(Icons.check_circle,color:Color(0xFF7DC49B),size:17),const SizedBox(width:5),Text((d['status']??'Confirmed').toString(),style:const TextStyle(color:Color(0xFF7DC49B),fontWeight:FontWeight.w700)),const Spacer(),const Text('View booking',style:TextStyle(color:FT.gold))])]))]));}
 Widget _timeline(Map x){final d=x['data'] as Map<String,dynamic>;final b=d['businesses'] is Map?Map<String,dynamic>.from(d['businesses']):{};final date=(d['reservation_date']??d['check_in']??'').toString();final time=(d['reservation_time']??d['check_in']??'').toString();return Padding(padding:const EdgeInsets.only(bottom:24),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[SizedBox(width:66,child:Text(date.length>=10?date.substring(5,10):date,style:const TextStyle(color:FT.gold,fontSize:12,fontWeight:FontWeight.w700))),Column(children:[Container(width:10,height:10,decoration:const BoxDecoration(color:FT.gold,shape:BoxShape.circle)),Container(width:1,height:52,color:const Color(0xFF2A2C2D))]),const SizedBox(width:20),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(b['name']??'FineTime experience',style:const TextStyle(color:FT.ivory,fontSize:18,fontWeight:FontWeight.w800,fontFamily:'serif')),const SizedBox(height:5),Text(time+' · '+(b['city']??'Ethiopia').toString(),style:const TextStyle(color:FT.muted,fontSize:12))]))]));}
}
class _Empty extends StatelessWidget{final String text;final IconData icon;const _Empty(this.text,this.icon);@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.symmetric(vertical:45),child:Column(children:[Icon(icon,color:FT.muted,size:50),const SizedBox(height:12),Text(text,textAlign:TextAlign.center,style:const TextStyle(color:FT.muted))]));}
